apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-non-local
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-non-local 
  name: test-non-local
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-non-local 
